server:
  port: 8443
  ssl:
    key-store: ssl-keystore.p12
    key-store-password: cfsstore-pw
    keyStoreType: PKCS12
    keyAlias: tomcat

sso:
  useReverseProxy: false
  entityId: localhost
  entityBaseURL: https://localhost:8443
