logging:
  level:
    uk.gov.ons.ctp.integration.censusfieldsvc: INFO
    uk.gov.ons.ctp.common: INFO
    org.springframework: INFO
    org.springframework.security.saml: INFO
    com.github.ulisesbocchio: DEBUG
    PROTOCOL_MESSAGE: DEBUG
    
domain: localhost

server:
  port: 443
  ssl:  # Enable ssl, as the G Suite IDP will only work with a https SAML endpoint
    key-store: classpath:localhost-ssl-keystore.p12
    key-store-password: cfsstore-pw
    keyStoreType: PKCS12
    keyAlias: tomcat

sso:
  useReverseProxy: false
  entityId: ${domain}
  entityBaseURL: https://${domain}:443
